format = '''
[â”Œî½ˆâ”€â”€â”€ï‹œâ”€â”€ï‹œâ”€â”€ï‹œâ”€â”€î½ˆâ”€â”€â”€ï‹œâ”€â”€ï‹œâ”€â”€î½ˆâ”€â”€â”€MERRY CHRISTMASâ”€â”€î½ˆâ”€â”€â”€ï‹œâ”€â”€ï‹œâ”€â”€î½ˆâ”€â”€â”€ï‹œ](bold bg:red)[î‚´](bold fg:red)
[â”‚](bold bg:red)[ã€”](bold bg:green)$os[ ã€•](bold bg:green)[ã€”](bold bg:green)$username[ã€•](bold bg:green)[ã€”](bold bg:green)$directory[ã€•](bold bg:green)[î‚´](bold fg:green)
[â””â”€ ğŸ¬ ](bold bg:red)[î‚´](bold fg:red)$character '''

# A new line at the beginning
add_newline = true

[line_break]
disabled = false

[character]
success_symbol = "[ğŸ„](bold green)"
error_symbol = "[ğŸ](bold red)"

[username]
show_always = true
format = '[$user](bold bg:green)'
disabled = false

# Display OS
[os]
disabled = false # Disabled by default
style = "bold bg:green"

# Supported OS Symbols in this prompt
[os.symbols]
AlmaLinux = "ïŒ"
Alpine = "ïŒ€"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ïŒŸ"
CachyOS = "î±"
CentOS = "î¼½"
Debian = "î½"
DragonFly = "î»¸"
EndeavourOS = "ïŒ¢ "
Fedora = "îŸ™"
FreeBSD = "ïŠ"
Garuda = "ïŒ·"
Gentoo = "îŸ¦"
Kali = "ïŒ§"
Linux = "ï…¼"
Macos = "îœ‘"
Manjaro = "ïŒ’"
Mint = "ó°£­"
NetBSD = "ğŸš© "
NixOS = "ó±„…"
Nobara = "ï€"
OpenBSD = "ïŒ¨"
openSUSE = "î¡—"
OracleLinux = "ó°«¼"
Pop = "ïŒª"
Raspbian = "îœ¢"
Redhat = "î½"
RedHatEnterprise = "î½"
RockyLinux = "î¢‘"
Solus = "ïŒ­"
SUSE = "î½­"
Ubuntu = "î½²"
Unknown = "î¯ƒ"
Void = "ïŒ®"
Windows = "î˜ª"

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold bg:green"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[$all_status$ahead_behind ]($style)'


[time]
disabled = false
time_format = "%I:%M %P"
format = "[ $time ]($style)"
style = "bold bg:green"

[cmd_duration]
disabled = false
min_time = 2000
format = '[ Took $duration!]($style)'
style = "bold bg:green"

[c]
symbol = "C "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version(-$name) )]($style)'
disabled = false

[cpp]
symbol = "î™† "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version(-$name) )]($style)'
disabled = false

[golang]
symbol = "î "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[haskell]
symbol = "ó°²’ "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[java]
symbol = "îœ¸ "
style = "bg:#434c5e fg:#ffffff"
format = '[ ${symbol}(${version} )]($style)'
disabled = false

[nodejs]
symbol = "îµ„ "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[rust]
symbol = "î¨ "
style = "bg:#434c5e fg:#ffffff"
format = '[ $symbol($version )]($style)'
disabled = false

[python]
symbol = "îœ¼ "
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bg:#434c5e fg:#ffffff"
disabled = false
